apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: Ym9vay1yZHMuY25jdTA0YXNlZWgwLmFwLXNvdXRoZWFzdC0yLnJkcy5hbWF6b25hd3MuY29t
  db_username: YWRtaW4=
  db_password: c3JpdmFyZGhhbg==
